export const AlertType = {
  GEOFENCE_ENTER: 'GEOFENCE_ENTER',
  GEOFENCE_EXIT: 'GEOFENCE_EXIT',
  OVERSPEED: 'OVERSPEED',
  NO_MOVEMENT: 'NO_MOVEMENT',
  LOW_BATTERY: 'LOW_BATTERY',
  SIGNAL_LOSS: 'SIGNAL_LOSS',
  SUSPICIOUS_STOP: 'SUSPICIOUS_STOP',
  HIGH_TEMPERATURE: 'HIGH_TEMPERATURE',
  DEVICE_OFFLINE: 'DEVICE_OFFLINE',
};

export const NotificationChannel = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  PUSH: 'PUSH',
  CONSOLE: 'CONSOLE',
};
